#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build fast Serbia-wide VIIRS raster overlays from the 500 m JSON pixels.

The scientific source values remain the compact VIIRS sample points generated by
``build_serbia_viirs.py``.  This helper creates two *display* rasters in Web
Mercator geometry so Leaflet can render them as a single image overlay instead
of parsing/drawing hundreds of thousands of JSON points in the browser:

* ``surface.webp`` — a lightly smoothed continuous-looking heat surface;
* ``raw.webp``     — unsmoothed cell view for inspecting the native ~500 m grid.

The rasters are clipped to the same national mask and are display products only.
Point queries on the website continue to use the source JSON pixels directly.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Tuple

from PIL import Image, ImageChops, ImageDraw, ImageFilter

JSON_FLAGS = dict(ensure_ascii=False, indent=2)
RADIUS_M = 6378137.0


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Dict[str, Any]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(payload, **JSON_FLAGS) + "\n", encoding="utf-8")
    tmp.replace(path)


def clamp_lat(lat: float) -> float:
    return max(-85.05112878, min(85.05112878, lat))


def mercator_y(lat: float) -> float:
    r = math.radians(clamp_lat(lat))
    return math.log(math.tan(math.pi / 4.0 + r / 2.0))


def xy_for(lon: float, lat: float, bbox: Sequence[float], width: int, height: int) -> Tuple[float, float]:
    min_lon, min_lat, max_lon, max_lat = map(float, bbox)
    x = (lon - min_lon) / (max_lon - min_lon) * (width - 1)
    y_top = mercator_y(max_lat)
    y_bottom = mercator_y(min_lat)
    y = (y_top - mercator_y(lat)) / (y_top - y_bottom) * (height - 1)
    return x, y


def image_dimensions(bbox: Sequence[float], width: int, max_height: int) -> Tuple[int, int]:
    min_lon, min_lat, max_lon, max_lat = map(float, bbox)
    dx = math.radians(max_lon - min_lon)
    dy = mercator_y(max_lat) - mercator_y(min_lat)
    height = int(round(width * dy / max(dx, 1e-12)))
    return width, max(256, min(max_height, height))


def iter_points(period_root: Path, index: Dict[str, Any]) -> Iterable[Tuple[float, float, float]]:
    for tile in index.get("tiles") or []:
        rel = tile.get("file")
        if not rel:
            continue
        path = period_root / str(rel)
        if not path.is_file():
            continue
        data = read_json(path)
        for px in data.get("pixels") or []:
            if isinstance(px, list) and len(px) >= 3:
                try:
                    yield float(px[0]), float(px[1]), float(px[2])
                except (TypeError, ValueError):
                    pass


def lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


# Continuous display palette anchored on the public statistical class breaks.
ANCHORS = [
    # v1.3.3: stronger visual separation between public classes.
    # Thresholds are unchanged; only the display palette is refined.
    (0.00, (15, 45, 31)),
    (0.25, (30, 68, 46)),
    (0.50, (77, 123, 56)),
    (1.00, (174, 199, 66)),
    (1.50, (244, 216, 64)),   # clear yellow inside the 1–3 class
    (3.00, (240, 169, 62)),
    (10.0, (238, 117, 70)),
    (30.0, (226, 68, 76)),
]


def rgb_for(value: float) -> Tuple[int, int, int]:
    v = max(0.0, float(value))
    if v <= ANCHORS[0][0]:
        return ANCHORS[0][1]
    for i in range(1, len(ANCHORS)):
        v0, c0 = ANCHORS[i - 1]
        v1, c1 = ANCHORS[i]
        if v <= v1:
            # Log interpolation is visually more stable across the long VIIRS tail.
            if v0 > 0:
                t = (math.log(max(v, v0)) - math.log(v0)) / (math.log(v1) - math.log(v0))
            else:
                t = (v - v0) / (v1 - v0)
            t = max(0.0, min(1.0, t))
            return tuple(int(round(lerp(c0[j], c1[j], t))) for j in range(3))
    return ANCHORS[-1][1]


def geometry_from_boundary(path: Path) -> Dict[str, Any]:
    data = read_json(path)
    if data.get("type") == "FeatureCollection":
        return (data.get("features") or [{}])[0].get("geometry") or {}
    if data.get("type") == "Feature":
        return data.get("geometry") or {}
    return data


def polygons(geometry: Dict[str, Any]) -> List[Any]:
    typ = geometry.get("type")
    coords = geometry.get("coordinates") or []
    if typ == "Polygon":
        return [coords]
    if typ == "MultiPolygon":
        return list(coords)
    raise RuntimeError(f"Unsupported boundary geometry: {typ}")


def build_mask(geometry: Dict[str, Any], bbox: Sequence[float], size: Tuple[int, int]) -> Image.Image:
    width, height = size
    mask = Image.new("L", size, 0)
    draw = ImageDraw.Draw(mask)
    for poly in polygons(geometry):
        if not poly:
            continue
        outer = [xy_for(float(p[0]), float(p[1]), bbox, width, height) for p in poly[0]]
        draw.polygon(outer, fill=255)
        for hole in poly[1:]:
            ring = [xy_for(float(p[0]), float(p[1]), bbox, width, height) for p in hole]
            draw.polygon(ring, fill=0)
    return mask


def resolve_period(results: Path, kind: str, period: str) -> str:
    if period != "auto":
        return period
    root = read_json(results / "index.json")
    value = root.get("latest_year" if kind == "year" else "latest_month")
    if not value:
        raise RuntimeError(f"Cannot resolve latest {kind}")
    return str(value)


def build_one(results: Path, boundary: Path, kind: str, period: str, width: int, max_height: int, quality: int) -> None:
    folder = "years" if kind == "year" else "months"
    period_root = results / folder / period
    index_path = period_root / "index.json"
    if not index_path.is_file():
        raise RuntimeError(f"Missing {index_path}")
    index = read_json(index_path)
    bbox = index.get("country", {}).get("bbox")
    if not isinstance(bbox, list) or len(bbox) < 4:
        raise RuntimeError("Period index has no country bbox")
    size = image_dimensions(bbox, width, max_height)
    w, h = size
    print(f"SURFACE {kind} {period}: {w}x{h}")

    geometry = geometry_from_boundary(boundary)
    mask = build_mask(geometry, bbox, size)
    raw = Image.new("RGBA", size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(raw, "RGBA")

    # 500 m in Web-Mercator x metres -> source-cell footprint in output pixels.
    min_lon, _min_lat, max_lon, _max_lat = map(float, bbox)
    mercator_width_m = RADIUS_M * math.radians(max_lon - min_lon)
    metres_per_px = mercator_width_m / max(1, w - 1)
    half = max(1.0, min(4.0, 0.58 * 500.0 / max(metres_per_px, 1e-9)))

    count = 0
    for lon, lat, value in iter_points(period_root, index):
        x, y = xy_for(lon, lat, bbox, w, h)
        if x < -half or y < -half or x > w - 1 + half or y > h - 1 + half:
            continue
        r, g, b = rgb_for(value)
        draw.rectangle((x - half, y - half, x + half, y + half), fill=(r, g, b, 220))
        count += 1
    if count == 0:
        raise RuntimeError(f"No source pixels for {kind} {period}")

    # Apply national alpha mask to raw data.
    alpha = raw.getchannel("A")
    raw.putalpha(ImageChops.multiply(alpha, mask))

    # Smooth display surface. Blur just enough to remove point/cell artefacts,
    # while keeping regional gradients and settlement hotspots readable.
    smooth = raw.filter(ImageFilter.GaussianBlur(radius=max(2.0, half * 1.05)))
    smooth_alpha = smooth.getchannel("A")
    smooth.putalpha(ImageChops.multiply(smooth_alpha, mask))

    raw_path = period_root / "raw.webp"
    heat_path = period_root / "surface.webp"
    raw.save(raw_path, "WEBP", quality=quality, method=6, lossless=False)
    smooth.save(heat_path, "WEBP", quality=quality, method=6, lossless=False)

    index["surface"] = {
        "projection": "EPSG:3857",
        "bbox_wgs84": [float(x) for x in bbox],
        "width": w,
        "height": h,
        "heat_file": "surface.webp",
        "raw_file": "raw.webp",
        "source_scale_m": float(index.get("meta", {}).get("scale_m") or 500.0),
        "render": "pre-rendered WebP overlay clipped to the national mask",
        "heat_note": "Display-only smoothed raster. Point values are calculated from source VIIRS pixels, not read from image colors.",
        "raw_note": "Display-only unsmoothed raster of the native pixel grid.",
    }
    write_json(index_path, index)
    print(f"OK {heat_path} ({heat_path.stat().st_size:,} B), {raw_path} ({raw_path.stat().st_size:,} B), source pixels={count:,}")


def main() -> int:
    p = argparse.ArgumentParser(description="Build fast WebP overlays for Serbia-wide VIIRS data")
    p.add_argument("--results-dir", default="public/results/serbia")
    p.add_argument("--boundary", default="public/boundaries/granica_srbije.geojson")
    p.add_argument("--kind", choices=["year", "month"], required=True)
    p.add_argument("--period", default="auto")
    p.add_argument("--width", type=int, default=2048)
    p.add_argument("--max-height", type=int, default=3072)
    p.add_argument("--quality", type=int, default=84)
    args = p.parse_args()
    if args.width < 512 or args.width > 4096:
        raise RuntimeError("--width must be 512..4096")
    results = Path(args.results_dir)
    period = resolve_period(results, args.kind, args.period)
    build_one(results, Path(args.boundary), args.kind, period, args.width, args.max_height, args.quality)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
